/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Anime } from "./Anime";
import { AnimeCountArgs } from "./AnimeCountArgs";
import { AnimeFindManyArgs } from "./AnimeFindManyArgs";
import { AnimeFindUniqueArgs } from "./AnimeFindUniqueArgs";
import { CreateAnimeArgs } from "./CreateAnimeArgs";
import { UpdateAnimeArgs } from "./UpdateAnimeArgs";
import { DeleteAnimeArgs } from "./DeleteAnimeArgs";
import { AnimeService } from "../anime.service";
@graphql.Resolver(() => Anime)
export class AnimeResolverBase {
  constructor(protected readonly service: AnimeService) {}

  async _animeItemsMeta(
    @graphql.Args() args: AnimeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Anime])
  async animeItems(@graphql.Args() args: AnimeFindManyArgs): Promise<Anime[]> {
    return this.service.animeItems(args);
  }

  @graphql.Query(() => Anime, { nullable: true })
  async anime(
    @graphql.Args() args: AnimeFindUniqueArgs
  ): Promise<Anime | null> {
    const result = await this.service.anime(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Anime)
  async createAnime(@graphql.Args() args: CreateAnimeArgs): Promise<Anime> {
    return await this.service.createAnime({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Anime)
  async updateAnime(
    @graphql.Args() args: UpdateAnimeArgs
  ): Promise<Anime | null> {
    try {
      return await this.service.updateAnime({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Anime)
  async deleteAnime(
    @graphql.Args() args: DeleteAnimeArgs
  ): Promise<Anime | null> {
    try {
      return await this.service.deleteAnime(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
